### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by H6ixty** [B3akers/FlyGuys#13]
sorry that i rage bro im just a little kid that has no knowledge

but how do I update the dll then I don't understand

and where is the character-> fields._data

sorry and what is misc in the mod menu

**Comment by H6ixty** [comment]
can you answer me please?

**Comment by B3akers** [comment]
If you have no knowledge or you can’t compile it and run I think you shouldn’t cheat at all. I released it for people who has some knowledge about game hacking

**Comment by H6ixty** [comment]
Bro realy i compile it easy and i want a answer for my Update qeustion please

**Comment by B3akers** [comment]
You have #Updates, only what you have to do is use Il2CppDumper and get offsets from script.json
