### ISSUE TITLE
Crash on Tiptoe

### ISSUE THREAD

**Issue by Yuvi721** [B3akers/FlyGuys#15]
Thanks for your work. It works great except i get crashes when i get the tiptoe round. I tried changing injectors but it doesn't solve the problem. Any idea where the problem could be?

Game log shows:
(UnityPlayer) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address'

**Comment by sateun1221** [comment]
I've tried building with virtual studio 2019 and I'm getting an error, do you know how to solve this?

**Comment by B3akers** [comment]
Next time attach debugger from visual studio it will show more informations which will help to solve it

**Comment by Yuvi721** [comment]
This time it happened on match fruit round but usually happens on tiptoe. This is the exception and the callstack

Exception thrown: read access violation.
**i** was nullptr.

Callstack
>	FlyGuys.dll!update() Line 467	C++
>FlyGuys.dll!dxgi_present::hooked(IDXGISwapChain * p_swap_chain, unsigned int sync_interval, unsigned int flags) Line 621	C++

Line 467 render.cpp:
auto current_object = i->object;

Hope this helps

**Comment by B3akers** [comment]
I added nullptr check let me know if crash still occurs
