### ISSUE TITLE
C3536, C2664

### ISSUE THREAD

**Issue by lavaman11** [B3akers/FlyGuys#21]
![dll](https://user-images.githubusercontent.com/17786848/90571220-9e543080-e1b1-11ea-874d-ae745cc74861.PNG)
I've tried to fix it somehow, but haven't had any success. Can someone help me?

**Comment by fir3z** [comment]
![image](https://user-images.githubusercontent.com/24984344/90572473-1c004800-e182-11ea-9a32-1d14cb283771.png)
Change this field in the project settings to "Use Multi-Byte Character Set", then rebuild the solution.

**Comment by lavaman11** [comment]
thanks^^

**Comment by fir3z** [comment]
You should probably close the issue lol.
