### ISSUE TITLE
inject fail

### ISSUE THREAD

**Issue by huajidadiguo** [B3akers/FlyGuys#6]
uh,i use visual studio and get the dll but it says inject fail when i try to inject.extreme and xenos both can't.i try to use other method but still didn't work.
![image](https://user-images.githubusercontent.com/63135252/89987863-4bf6a980-dcb1-11ea-8a73-b2505a06395f.png)

**Comment by H6ixty** [comment]
Hi how do you get the dll at all

**Comment by GirlWithCheats** [comment]
they pushed an update today, VAC is enabled now!
