### ISSUE TITLE
VAC BANNED - DETECTED

### ISSUE THREAD

**Issue by GirlWithCheats** [B3akers/FlyGuys#7]
DO NOT USE internal version, wait for external version, got a VAC BAN after 1/2 Game.

EDIT: they pushed an update 10 hours ago

EDIT2: looks like its an Developer VAC BAN [https://support.steampowered.com/kb_article.php?ref=6899-IOSK-9514&l=english](https://support.steampowered.com/kb_article.php?ref=6899-IOSK-9514&l=english)

**Comment by Nexxol1** [comment]
Hi, sorry but im new to modding, what do you mean by external?

**Comment by H6ixty** [comment]
nope its not true i played yet for 4 hours and nothing happens.

**Comment by onra2** [comment]
the game isn't vac protected retard

**Comment by fir3z** [comment]
Just as an update for anyone looking through closed issues, the game itself does not currently have an anti-cheat and it is not detected. OP is talking about a manual Developer Ban issued by the development team of Fall Guys, this may only happen if you were reported for cheating and caught afterwards.
